// src/pages/Checkout.tsx
import React, { useState } from 'react';
import { motion } from 'motion/react';
import { useCart } from '../context/CartContext';
import { useNavigate, Link } from 'react-router-dom';
import { ChevronLeft, CreditCard, Truck, ShieldCheck, CheckCircle2 } from 'lucide-react';

const Checkout = () => {
  const { cart, cartTotal, clearCart } = useCart();
  const navigate = useNavigate();
  const [isOrdered, setIsOrdered] = useState(false);

  const [formData, setFormData] = useState({
    email: '',
    firstName: '',
    lastName: '',
    address: '',
    city: '',
    postalCode: '',
    phone: ''
  });

  if (cart.length === 0 && !isOrdered) {
    return (
      <div className="pt-40 pb-24 px-6 bg-brand-timber min-h-screen text-brand-cream flex flex-col items-center justify-center text-center">
        <h2 className="text-4xl font-black uppercase italic tracking-tighter mb-6">Your cart is empty.</h2>
        <Link to="/shop" className="bg-brand-rust text-white px-10 py-4 rounded-full font-black uppercase italic tracking-widest text-[10px]">Start Shopping</Link>
      </div>
    );
  }

  const handleSubmit = (e: React.FormEvent) => {
    e.preventDefault();
    
    const paystackKey = import.meta.env.VITE_PAYSTACK_PUBLIC_KEY || 'pk_live_73239c12b24d20f04440820c385734aa2919d817';

    const handler = (window as any).PaystackPop.setup({
      key: paystackKey,
      email: formData.email,
      amount: Math.round(cartTotal * 100), // in cents
      currency: 'ZAR',
      ref: `AFR-${Date.now()}-${Math.floor(Math.random() * 10000)}`,
      metadata: {
        custom_fields: [
          {
            display_name: "Customer Name",
            variable_name: "customer_name",
            value: `${formData.firstName} ${formData.lastName}`
          },
          {
            display_name: "Phone Number",
            variable_name: "phone_number",
            value: formData.phone
          },
          {
            display_name: "Delivery Address",
            variable_name: "delivery_address",
            value: `${formData.address}, ${formData.city}, ${formData.postalCode}`
          }
        ]
      },
      callback: function(response: any) {
        // Send email with order details via FormSubmit
        const orderSummary = cart.map(item => `${item.quantity}x ${item.name} (${item.selectedWeight}g, ${item.selectedFlavor}) - R${((item.prices[item.selectedWeight] || 0) * item.quantity).toFixed(2)}`).join('\n');
        
        fetch('https://formsubmit.co/ajax/sales@africutbiltong.co.za', {
          method: 'POST',
          headers: {
            'Content-Type': 'application/json',
            'Accept': 'application/json'
          },
          body: JSON.stringify({
            name: `${formData.firstName} ${formData.lastName}`,
            email: formData.email,
            phone: formData.phone,
            address: `${formData.address}, ${formData.city}, ${formData.postalCode}`,
            order_total: `R${cartTotal.toFixed(2)}`,
            order_details: orderSummary,
            _subject: `New Order Received - R${cartTotal.toFixed(2)}`,
            _template: 'table'
          })
        }).then(res => res.json())
          .then(data => console.log('Order email sent', data))
          .catch(err => console.error('Failed to send email', err));

        setIsOrdered(true);
        clearCart();
      },
      onClose: function() {
        alert('Payment was cancelled. Please try again to complete your order.');
      }
    });

    handler.openIframe();
  };

  if (isOrdered) {
    return (
      <div className="pt-40 pb-24 px-6 bg-brand-timber min-h-screen text-brand-cream flex flex-col items-center justify-center text-center">
        <motion.div 
          initial={{ scale: 0.8, opacity: 0 }}
          animate={{ scale: 1, opacity: 1 }}
          className="max-w-md w-full space-y-8"
        >
          <div className="w-24 h-24 bg-brand-rust rounded-full mx-auto flex items-center justify-center shadow-3xl">
            <CheckCircle2 className="w-12 h-12 text-white" />
          </div>
          <div className="space-y-4">
            <h1 className="text-5xl font-black tracking-tighter uppercase italic leading-none">Order Placed Successfully!</h1>
            <p className="text-brand-cream/40 font-medium italic">Thank you for your purchase. We've sent a confirmation email with your order details.</p>
          </div>
          <Link 
            to="/" 
            className="inline-block bg-brand-rust text-white px-12 py-5 rounded-full font-black uppercase italic tracking-widest text-xs shadow-3xl hover:bg-brand-spiced transition-all"
          >
            Back to Home
          </Link>
        </motion.div>
      </div>
    );
  }

  return (
    <div className="pt-40 pb-24 bg-brand-timber min-h-screen text-brand-cream">
      <div className="max-w-7xl mx-auto px-6">
        <Link to="/shop" className="inline-flex items-center space-x-2 text-brand-cream/40 hover:text-brand-rust transition-colors mb-12 uppercase text-[10px] font-black tracking-widest italic leading-none">
           <ChevronLeft className="w-4 h-4" />
           <span>Back to Shop</span>
        </Link>

        <h1 className="text-6xl font-black tracking-tighter mb-16 uppercase italic leading-none">Checkout</h1>

        <div className="grid grid-cols-1 lg:grid-cols-12 gap-16">
          {/* Checkout Form */}
          <div className="lg:col-span-7">
            <form onSubmit={handleSubmit} className="space-y-12">
              <section className="space-y-8">
                <div className="flex items-center space-x-4 border-b border-white/5 pb-4">
                  <span className="w-8 h-8 rounded-full bg-brand-rust text-white flex items-center justify-center font-black text-xs italic">01</span>
                  <h3 className="text-xs font-black uppercase tracking-widest italic">Customer Information</h3>
                </div>
                <div className="grid grid-cols-1 gap-6">
                  <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
                    <div className="space-y-2">
                      <label className="text-[9px] font-black uppercase tracking-widest text-brand-cream/30 italic">Email Address</label>
                      <input 
                        required
                        type="email" 
                        className="w-full bg-brand-surface border border-white/5 rounded-2xl p-5 text-sm font-medium italic focus:border-brand-rust/50 focus:outline-none transition-all placeholder:text-brand-cream/10"
                        placeholder="e.g. customer@example.com"
                        value={formData.email}
                        onChange={e => setFormData({...formData, email: e.target.value})}
                      />
                    </div>
                    <div className="space-y-2">
                      <label className="text-[9px] font-black uppercase tracking-widest text-brand-cream/30 italic">Phone Number</label>
                      <input 
                        required
                        type="tel" 
                        className="w-full bg-brand-surface border border-white/5 rounded-2xl p-5 text-sm font-medium italic focus:border-brand-rust/50 focus:outline-none transition-all placeholder:text-brand-cream/10"
                        placeholder="e.g. +27 82 123 4567"
                        value={formData.phone}
                        onChange={e => setFormData({...formData, phone: e.target.value})}
                      />
                    </div>
                  </div>
                  <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
                    <div className="space-y-2">
                      <label className="text-[9px] font-black uppercase tracking-widest text-brand-cream/30 italic">First Name</label>
                      <input 
                        required
                        type="text" 
                        className="w-full bg-brand-surface border border-white/5 rounded-2xl p-5 text-sm font-medium italic focus:border-brand-rust/50 focus:outline-none transition-all"
                        value={formData.firstName}
                        onChange={e => setFormData({...formData, firstName: e.target.value})}
                      />
                    </div>
                    <div className="space-y-2">
                      <label className="text-[9px] font-black uppercase tracking-widest text-brand-cream/30 italic">Last Name</label>
                      <input 
                        required
                        type="text" 
                        className="w-full bg-brand-surface border border-white/5 rounded-2xl p-5 text-sm font-medium italic focus:border-brand-rust/50 focus:outline-none transition-all"
                        value={formData.lastName}
                        onChange={e => setFormData({...formData, lastName: e.target.value})}
                      />
                    </div>
                  </div>
                </div>
              </section>

              <section className="space-y-8">
                <div className="flex items-center space-x-4 border-b border-white/5 pb-4">
                  <span className="w-8 h-8 rounded-full bg-brand-rust text-white flex items-center justify-center font-black text-xs italic">02</span>
                  <h3 className="text-xs font-black uppercase tracking-widest italic">Shipping Address</h3>
                </div>
                <div className="space-y-6">
                  <div className="space-y-2">
                    <label className="text-[9px] font-black uppercase tracking-widest text-brand-cream/30 italic">Address</label>
                    <input 
                      required
                      type="text" 
                      className="w-full bg-brand-surface border border-white/5 rounded-2xl p-5 text-sm font-medium italic focus:border-brand-rust/50 focus:outline-none transition-all"
                      value={formData.address}
                      onChange={e => setFormData({...formData, address: e.target.value})}
                    />
                  </div>
                  <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
                    <div className="space-y-2">
                      <label className="text-[9px] font-black uppercase tracking-widest text-brand-cream/30 italic">City</label>
                      <input 
                        required
                        type="text" 
                        className="w-full bg-brand-surface border border-white/5 rounded-2xl p-5 text-sm font-medium italic focus:border-brand-rust/50 focus:outline-none transition-all"
                        value={formData.city}
                        onChange={e => setFormData({...formData, city: e.target.value})}
                      />
                    </div>
                    <div className="space-y-2">
                      <label className="text-[9px] font-black uppercase tracking-widest text-brand-cream/30 italic">Postal Code</label>
                      <input 
                        required
                        type="text" 
                        className="w-full bg-brand-surface border border-white/5 rounded-2xl p-5 text-sm font-medium italic focus:border-brand-rust/50 focus:outline-none transition-all"
                        value={formData.postalCode}
                        onChange={e => setFormData({...formData, postalCode: e.target.value})}
                      />
                    </div>
                  </div>
                </div>
              </section>

              <div className="space-y-4">
                {cartTotal < 250 && (
                  <div className="bg-brand-rust/20 border border-brand-rust/50 rounded-2xl p-4 text-center">
                    <p className="text-brand-cream font-black uppercase tracking-widest text-xs italic">
                      Minimum order value is R250.
                    </p>
                    <p className="text-brand-cream/50 font-medium text-[10px] uppercase tracking-wider italic mt-1">
                      Please add R{(250 - cartTotal).toFixed(2)} more to your cart to checkout.
                    </p>
                  </div>
                )}
                
                <button 
                  type="submit"
                  disabled={cartTotal < 250}
                  className={`w-full py-8 rounded-3xl font-black uppercase italic tracking-[0.2em] text-sm shadow-3xl transition-all transform active:scale-[0.98] flex items-center justify-center space-x-4 ${
                    cartTotal < 250 
                      ? 'bg-brand-timber border border-white/5 text-brand-cream/20 cursor-not-allowed' 
                      : 'bg-brand-rust text-white hover:bg-brand-spiced cursor-pointer'
                  }`}
                >
                  <CreditCard className="w-5 h-5" />
                  <span>Pay Now</span>
                </button>
              </div>
            </form>
          </div>

          {/* Order Summary */}
          <div className="lg:col-span-5">
            <div className="bg-brand-surface border border-white/5 p-10 rounded-[3rem] sticky top-32">
              <h4 className="text-xs font-black uppercase tracking-widest text-brand-rust italic mb-10 pb-4 border-b border-white/5">Order Summary</h4>
              
              <div className="space-y-8 mb-12 max-h-[40vh] overflow-y-auto no-scrollbar pr-4">
                {cart.map(item => (
                  <div key={`${item.id}-${item.selectedWeight}-${item.selectedFlavor}`} className="flex justify-between items-center group">
                    <div className="flex items-center space-x-6">
                       <div className="w-16 h-16 rounded-2xl bg-brand-timber overflow-hidden border border-white/5">
                          <img src={item.image} alt={item.name} className="w-full h-full object-cover" />
                       </div>
                       <div>
                          <p className="text-xs font-black uppercase italic italic tracking-tight">{item.name}</p>
                          <p className="text-[9px] text-brand-cream/30 uppercase font-black tracking-widest italic">{item.quantity}x • {item.selectedWeight}g • {item.selectedFlavor}</p>
                       </div>
                    </div>
                    <p className="text-xs font-black italic">R{((item.prices[item.selectedWeight] || 0) * item.quantity).toFixed(2)}</p>
                  </div>
                ))}
              </div>

              <div className="space-y-4 pt-10 border-t border-white/5 mb-10">
                <div className="flex justify-between text-[10px] font-black uppercase tracking-widest text-brand-cream/30 italic">
                  <span>Subtotal</span>
                  <span>R{cartTotal.toFixed(2)}</span>
                </div>
                <div className="flex justify-between text-[10px] font-black uppercase tracking-widest text-brand-rust italic">
                  <span>Shipping Cost</span>
                  <span>{cartTotal >= 500 ? 'Free' : 'Calculated at dispatch'}</span>
                </div>
              </div>

              <div className="flex justify-between items-end">
                <span className="text-[10px] font-black uppercase tracking-widest italic">Order Total</span>
                <span className="text-5xl font-black text-brand-rust italic tracking-tighter leading-none">R{cartTotal.toFixed(2)}</span>
              </div>

              <div className="mt-12 grid grid-cols-2 gap-4">
                <div className="flex items-center space-x-3 text-[9px] font-black uppercase tracking-widest text-brand-cream/20 italic">
                   <Truck className="w-4 h-4 text-brand-rust" />
                   <span>Gauteng dispatch</span>
                </div>
                <div className="flex items-center space-x-3 text-[9px] font-black uppercase tracking-widest text-brand-cream/20 italic">
                   <ShieldCheck className="w-4 h-4 text-brand-rust" />
                   <span>Secured network</span>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  );
};

export default Checkout;

// src/routes/(public)/checkout/+page.svelte
<script>
	import { cart } from '$lib/stores/cart.svelte.js'; // Ensure .svelte.js extension
	import { onMount } from 'svelte';
	import { fade, slide } from 'svelte/transition';
	import { goto } from '$app/navigation';
	import Icon from '@iconify/svelte';
	import { page } from '$app/stores';

	let { data } = $props();
	const { user, addresses } = data;

	// Reactive Cart State
	let items = $derived(cart.items);
	let total = $derived(cart.total);
	let currency = $derived(cart.currency);
	
	// Form State
	let currentStep = $state('address'); // 'address' | 'payment' | 'polling'
	let selectedAddressId = $state(addresses.find(a => a.isDefault)?.id || addresses[0]?.id || null);
	let paymentMethod = $state(currency === 'ZAR' ? 'card' : 'ecocash');
	let mobilePhone = $state('');
	
	// Status State
	let isProcessing = $state(false);
	let errorMsg = $state('');
	let pollingMsg = $state('');
	let pollInterval;

	onMount(() => {
		if (cart.items.length === 0) {
			goto('/store');
		}
		return () => { if (pollInterval) clearInterval(pollInterval); }
	});

	function formatPrice(cents) {
		const symbol = currency === 'ZAR' ? 'R' : '$';
		return `${symbol}${(cents / 100).toFixed(2)}`;
	}

	async function handlePayment() {
		if (!selectedAddressId) {
			errorMsg = 'Please select a shipping address.';
			return;
		}
		
		isProcessing = true;
		errorMsg = '';

		try {
			const payload = {
				items: items.map(i => ({ variantId: i.variantId, quantity: i.quantity })),
				currency,
				shippingAddressId: selectedAddressId,
				paymentMethod,
				phone: paymentMethod === 'ecocash' ? mobilePhone : undefined
			};

			const res = await fetch('/api/store/checkout/initiate', {
				method: 'POST',
				headers: { 'Content-Type': 'application/json' },
				body: JSON.stringify(payload)
			});

			const result = await res.json();
			if (!res.ok) throw new Error(result.message || 'Payment initiation failed.');

			// Handle Redirect (Card) or Polling (Mobile Money)
			if (result.redirectUrl) {
				pollingMsg = "Redirecting to secure payment gateway...";
				currentStep = 'polling';
				window.location.href = result.redirectUrl;
			} else if (result.pollUrl) {
				currentStep = 'polling';
				pollingMsg = `Payment request sent to ${mobilePhone}. Please check your phone to authorize.`;
				startPolling(result.orderPublicId);
			}

		} catch (e) {
			console.error(e);
			errorMsg = e.message;
			isProcessing = false;
		}
	}

	function startPolling(orderPublicId) {
		pollInterval = setInterval(async () => {
			try {
				const res = await fetch(`/api/store/orders/status/${orderPublicId}`);
				const data = await res.json();

				if (data.status === 'paid') {
					clearInterval(pollInterval);
					cart.clear();
					goto(`/checkout/success?order=${orderPublicId}`);
				} else if (data.status === 'cancelled' || data.status === 'failed') {
					clearInterval(pollInterval);
					errorMsg = "Payment failed or was cancelled. Please try again.";
					currentStep = 'payment';
					isProcessing = false;
				}
			} catch (e) {
				// Ignore polling errors, just retry
			}
		}, 3000);

		// Timeout after 60s
		setTimeout(() => {
			if (currentStep === 'polling') {
				clearInterval(pollInterval);
				errorMsg = "Payment verification timed out. Please check your order history.";
				currentStep = 'payment';
				isProcessing = false;
			}
		}, 60000);
	}
</script>

<svelte:head>
	<title>Checkout | Vision AI</title>
</svelte:head>

<div class="min-h-screen bg-slate-50 pt-8 pb-24">
	<div class="mx-auto max-w-7xl px-6 lg:px-8">
		
		<!-- Minimal Header -->
		<div class="mb-12 flex items-center gap-4 border-b border-slate-200 pb-6">
			<a href="/" class="text-xl font-bold text-main">Vision AI Tech</a>
			<Icon icon="mdi:chevron-right" class="text-slate-300" />
			<span class="font-medium text-slate-500">Secure Checkout</span>
		</div>

		<div class="grid grid-cols-1 gap-x-16 gap-y-10 lg:grid-cols-5">
			
			<!-- LEFT: Steps & Forms -->
			<div class="lg:col-span-3">
				
				<!-- Progress Stepper -->
				<nav class="mb-10 flex items-center gap-6 text-sm font-bold">
					<button class="flex items-center gap-3 {currentStep === 'address' ? 'text-accent' : 'text-main'}">
						<div class="flex h-8 w-8 items-center justify-center rounded-full bg-current text-white shadow-sm">1</div>
						Shipping
					</button>
					<div class="h-px w-12 bg-slate-300"></div>
					<button class="flex items-center gap-3 {currentStep === 'payment' ? 'text-accent' : 'text-slate-400'}" disabled>
						<div class="flex h-8 w-8 items-center justify-center rounded-full border-2 border-current bg-white">2</div>
						Payment
					</button>
					<div class="h-px w-12 bg-slate-300"></div>
					<span class="text-slate-400">Confirmation</span>
				</nav>

				<!-- STEP 1: ADDRESS -->
				{#if currentStep === 'address'}
					<div in:fade>
						<div class="flex justify-between items-end mb-6">
                            <h2 class="text-2xl font-bold text-main">Shipping Address</h2>
                            <a href="/account/addresses" class="text-sm font-bold text-accent hover:underline flex items-center gap-1">
                                <Icon icon="mdi:plus" /> New Address
                            </a>
                        </div>
						
						{#if addresses.length > 0}
							<div class="space-y-4">
								{#each addresses as addr}
									<label class="group relative flex cursor-pointer items-start gap-4 rounded-xl border p-6 shadow-sm transition-all
										{selectedAddressId === addr.id ? 'border-accent bg-accent/5 ring-1 ring-accent' : 'border-slate-200 bg-white hover:border-slate-300'}">
										
                                        <div class="flex h-5 items-center">
                                            <input type="radio" bind:group={selectedAddressId} value={addr.id} class="h-4 w-4 text-accent focus:ring-accent" />
                                        </div>
                                        
										<div class="flex-1">
                                            <div class="flex justify-between items-center mb-1">
											    <span class="font-bold text-main">{addr.label}</span>
                                                {#if addr.isDefault}
                                                    <span class="text-[10px] font-bold uppercase tracking-wider text-slate-400 border border-slate-200 rounded px-2 py-0.5">Default</span>
                                                {/if}
                                            </div>
											<p class="text-sm text-slate-600 leading-relaxed">
												{addr.firstName} {addr.lastName}<br>
												{addr.address}, {addr.city}<br>
												{addr.state} {addr.zipCode}, {addr.country}
											</p>
										</div>
									</label>
								{/each}
							</div>
							<div class="mt-8 flex justify-end">
								<button 
									onclick={() => currentStep = 'payment'}
									disabled={!selectedAddressId}
									class="rounded-md bg-main px-8 py-3 font-bold text-light transition hover:bg-main/90 disabled:opacity-50 disabled:cursor-not-allowed shadow-lg"
								>
									Continue to Payment
								</button>
							</div>
						{:else}
							<div class="rounded-xl border border-dashed border-slate-300 bg-slate-50 p-12 text-center">
								<p class="text-slate-500">You don't have any saved addresses.</p>
								<a href="/account/addresses?redirectTo=/checkout" class="mt-4 inline-block rounded-md bg-white border border-slate-200 px-6 py-2 text-sm font-bold text-main shadow-sm hover:border-accent">
                                    Add New Address
                                </a>
							</div>
						{/if}
					</div>
				
				<!-- STEP 2: PAYMENT -->
				{:else if currentStep === 'payment'}
					<div in:fade>
						<h2 class="mb-6 text-2xl font-bold text-main">Payment Method</h2>
						
						{#if errorMsg}
							<div class="mb-6 rounded-md bg-red-50 p-4 text-sm font-bold text-red-600 border border-red-200 flex items-center gap-2">
                                <Icon icon="mdi:alert-circle" width="20" />
								{errorMsg}
							</div>
						{/if}

						<div class="space-y-4">
							{#if currency === 'USD'}
                                <!-- EcoCash -->
								<label class="flex cursor-pointer items-center gap-4 rounded-xl border p-4 transition-all hover:shadow-md {paymentMethod === 'ecocash' ? 'border-accent bg-accent/5 ring-1 ring-accent' : 'border-slate-200 bg-white'}">
									<input type="radio" bind:group={paymentMethod} value="ecocash" class="text-accent focus:ring-accent" />
									<div>
                                        <span class="font-bold text-main block">EcoCash / Mobile Money</span>
                                        <span class="text-xs text-slate-500">Instant mobile payment</span>
                                    </div>
                                    <Icon icon="mdi:cellphone-nfc" width="32" class="ml-auto text-slate-400" />
								</label>

								{#if paymentMethod === 'ecocash'}
									<div class="ml-0 sm:ml-8 p-6 rounded-lg bg-white border border-slate-200 shadow-inner" transition:slide>
										<label class="block text-xs font-bold uppercase tracking-wider text-slate-500 mb-2">Phone Number</label>
                                        <div class="relative">
                                            <div class="pointer-events-none absolute inset-y-0 left-0 flex items-center pl-3">
                                                <Icon icon="mdi:phone" class="text-slate-400" />
                                            </div>
										    <input type="tel" bind:value={mobilePhone} placeholder="0771234567" class="w-full rounded-md border-slate-300 pl-10 focus:border-accent focus:ring-accent" />
                                        </div>
                                        <p class="text-xs text-slate-400 mt-2">You will receive a USSD prompt on this number.</p>
									</div>
								{/if}
                                
                                <!-- Card -->
								<label class="flex cursor-pointer items-center gap-4 rounded-xl border p-4 transition-all hover:shadow-md {paymentMethod === 'card' ? 'border-accent bg-accent/5 ring-1 ring-accent' : 'border-slate-200 bg-white'}">
									<input type="radio" bind:group={paymentMethod} value="card" class="text-accent focus:ring-accent" />
									<div>
                                        <span class="font-bold text-main block">Visa / MasterCard</span>
                                        <span class="text-xs text-slate-500">Secured by Paynow</span>
                                    </div>
                                    <div class="ml-auto flex gap-2 text-slate-400">
                                        <Icon icon="mdi:credit-card" width="24" />
                                    </div>
								</label>
							{:else}
								<!-- ZAR Payment -->
								<label class="flex cursor-pointer items-center gap-4 rounded-xl border p-4 transition-all border-accent bg-accent/5 ring-1 ring-accent">
									<input type="radio" checked class="text-accent focus:ring-accent" />
									<div>
                                        <span class="font-bold text-main block">Credit/Debit Card</span>
                                        <span class="text-xs text-slate-500">Secured by Paystack</span>
                                    </div>
                                    <Icon icon="mdi:lock" width="24" class="ml-auto text-slate-400" />
								</label>
							{/if}
						</div>

						<div class="mt-8 flex justify-between items-center pt-8 border-t border-slate-200">
							<button onclick={() => currentStep = 'address'} class="text-sm font-bold text-slate-500 hover:text-main flex items-center gap-1">
								<Icon icon="mdi:arrow-left" /> Back
							</button>
							<button 
								onclick={handlePayment}
								disabled={isProcessing || (paymentMethod === 'ecocash' && !mobilePhone)}
								class="rounded-md bg-accent px-8 py-3 font-bold text-main shadow-lg transition-all hover:-translate-y-1 hover:shadow-xl disabled:opacity-50 disabled:cursor-not-allowed flex items-center gap-2"
							>
								{#if isProcessing}
                                    <Icon icon="mdi:loading" class="animate-spin" /> Processing...
                                {:else}
                                    Pay {formatPrice(total)} <Icon icon="mdi:check" />
                                {/if}
							</button>
						</div>
					</div>
				
				<!-- STEP 3: POLLING / REDIRECTING -->
				{:else if currentStep === 'polling'}
					<div in:fade class="flex flex-col items-center justify-center py-16 text-center bg-white rounded-2xl border border-slate-200 shadow-sm">
						<div class="mx-auto mb-6 h-16 w-16 animate-spin rounded-full border-4 border-slate-100 border-t-accent"></div>
						<h3 class="text-2xl font-bold text-main">Processing Payment</h3>
						<p class="mt-4 text-slate-600 max-w-md mx-auto leading-relaxed">{pollingMsg}</p>
						<div class="mt-8 rounded-full bg-amber-50 px-4 py-2 text-xs font-bold text-amber-700 border border-amber-200 flex items-center gap-2">
                            <Icon icon="mdi:alert-circle-outline" />
                            Do not close this window
                        </div>
					</div>
				{/if}
			</div>

			<!-- RIGHT: Order Summary -->
			<div class="lg:col-span-2">
				<div class="sticky top-24 rounded-xl bg-white p-6 shadow-xl ring-1 ring-black/5">
					<h3 class="font-bold text-main border-b border-slate-100 pb-4 mb-4">Order Summary</h3>
					<div class="space-y-4 max-h-[400px] overflow-y-auto pr-2 custom-scrollbar">
						{#each items as item}
							<div class="flex items-start gap-4">
								<div class="h-16 w-16 flex-shrink-0 rounded-md bg-slate-50 border border-slate-200 overflow-hidden relative">
									{#if item.image}
										<img src={item.image} alt={item.name} class="h-full w-full object-cover" />
									{/if}
									<span class="absolute -top-2 -right-2 flex h-5 w-5 items-center justify-center rounded-full bg-main text-xs font-bold text-white shadow-sm border border-white">
										{item.quantity}
									</span>
								</div>
								<div class="flex-1 min-w-0">
									<p class="text-sm font-bold text-main truncate">{item.name}</p>
									<p class="text-xs text-slate-500">{item.variantName}</p>
								</div>
								<p class="text-sm font-bold text-main whitespace-nowrap">{formatPrice(item.price * item.quantity)}</p>
							</div>
						{/each}
					</div>
					
					<div class="border-t border-slate-100 pt-4 mt-4 space-y-2">
						<div class="flex justify-between text-sm text-slate-600">
							<span>Subtotal</span>
							<span>{formatPrice(total)}</span>
						</div>
						<div class="flex justify-between text-sm text-slate-600">
							<span>Shipping</span>
							<span class="text-green-600 font-medium">Free</span>
						</div>
					</div>
					
					<div class="border-t border-slate-100 pt-4 mt-4 flex justify-between items-center">
						<span class="font-bold text-lg text-main">Total</span>
						<span class="font-bold text-3xl text-accent flex items-baseline gap-1">
							<span class="text-sm font-normal text-slate-400 mr-1">{currency}</span>
							{formatPrice(total).replace(currency === 'ZAR' ? 'R' : '$', '')}
						</span>
					</div>
				</div>
			</div>

		</div>
	</div>
</div>
